export const CAROUSELS = 'CAROUSELS'
export const STYLE_INFO = 'STYLE_INFO'
export const STYLE_BANNER = 'STYLE_BANNER'
export const EXPERT_LISTS = 'EXPERT_LISTS'
export const BOTTOM_CAROUSELS = 'BOTTOM_CAROUSELS'

export const TECHNICIAN_LIST = 'TECHNICIAN_LIST'
export const CURRENT_PAGE = 'CURRENT_PAGE'

export const EXPERT_DETAIL = 'EXPERT_DETAIL'
export const EXPERT_ATTRIBUTE = 'EXPERT_ATTRIBUTE'
export const EXPERT_RESEARCH = 'EXPERT_RESEARCH'

export const GET_USER_INFO = 'GET_USER_INFO'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const CHANGE_LOGIN_STATUS = 'CHANGE_LOGIN_STATUS'